apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: core-infrastructure
    - name: sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/security
  prune: true
  wait: true
